// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_middleware from "./routes/api/_middleware.ts";
import * as $api_questions from "./routes/api/questions.ts";
import * as $api_token from "./routes/api/token.ts";
import * as $config from "./routes/config.ts";
import * as $index from "./routes/index.tsx";
import * as $tester from "./routes/tester.tsx";
import * as $types from "./routes/types.ts";
import * as $server_tester from "./islands/server_tester.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/_middleware.ts": $api_middleware,
    "./routes/api/questions.ts": $api_questions,
    "./routes/api/token.ts": $api_token,
    "./routes/config.ts": $config,
    "./routes/index.tsx": $index,
    "./routes/tester.tsx": $tester,
    "./routes/types.ts": $types,
  },
  islands: {
    "./islands/server_tester.tsx": $server_tester,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
